name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install -f

      - name: Build Angular App
        run: npm run build -- --prod

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t bouhlelrochdi/mini-projet-devops-lab03:$GITHUB_SHA .

      - name: Login to Docker Hub
        run: echo dckr_pat_nQ15v5jnU09JdVw3IV6XmL4uOjU | docker login -u bouhlelrochdi --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push bouhlelrochdi/mini-projet-devops-lab03:latest