#project name
name: cicd

on:
  push:
    branches: main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: bouhlelrochdi
          password: dckr_pat_nQ15v5jnU09JdVw3IV6XmL4uOjU
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: bouhlelrochdi/mini-projet-devops-lab03:latest
          push: true
      